### ISSUE TITLE
Generated File Comment Does not Adhere to Golang Spec

### ISSUE THREAD

**Issue by icubbon** [edwarnicke/imports-gen#11]
According to https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source, the comment should be something akin to `// Code generated by imports-gen DO NOT EDIT.` so that it matches the regex in the link. This comment indicates that the file should not be linted.

**Comment by edwarnicke** [comment]
Ah... I did not know that... this also seems like it would fix #6 :)  Will get right on it :)
