### ISSUE TITLE
Import of "C" is created even though it is not a module

### ISSUE THREAD

**Issue by icubbon** [edwarnicke/imports-gen#12]
If there is an `import "C"` in a file, the autogenerated imports will create a line `_ "C"` which is not valid.

**Comment by edwarnicke** [comment]
Ah... thanks for pointing that out.  I don't use import "C" much, but that doesn't mean its not important. 

What would be the 'intelligent' way to handle import "C"?

**Comment by icubbon** [comment]
The `import "C"` line has a special meaning and doesn't correlate to a go mod download. So it should be probably be completely ignored/thrown out if it's found. Not sure the "intelligent" way to do that. 
In my autogenerate code I'm doing a `sed` to just rip it out of the generated file:
`//go:generate bash -c "sed -i '/_ \"C\"/d' ./internal/imports/imports.go"`

**Comment by edwarnicke** [comment]
Try changing:

```//go:generate bash -c "cd $(mktemp -d) && GO111MODULE=on go get github.com/edwarnicke/imports-gen@v1.0.1"```
to
```//go:generate bash -c "cd $(mktemp -d) && GO111MODULE=on go get github.com/edwarnicke/imports-gen@master```

and see if that solves your issues here and in #11.  If it does I'll cut a v1.0.2 release :)

**Comment by icubbon** [comment]
Yep that is working and solves both of those issues!

**Comment by edwarnicke** [comment]
Release v1.1.2 is out... highly recommend switching to that from master (friends don't let friends consume moving targets ;) ).
