### ISSUE TITLE
Generated imports are not formatted

### ISSUE THREAD

**Issue by denis-tingaikin** [edwarnicke/imports-gen#6]
## Steps to reproduce
1. Run imports-gen for the project with few deps.
2. Rug goimports linter.

**Actual**: goimports fixes format for the generated file.
**Expected**: goimports should do nothing for the generated file.

**Comment by edwarnicke** [comment]
:)  Any thoughts on how to programmatically fix this?  I looked around a bit for a sort that would do goimport sorts... but didn't find one :(

**Comment by denis-tingaikin** [comment]
They use more smart sort based on short package name and strings distance, let me find it :)

**Comment by denis-tingaikin** [comment]
https://github.com/golang/tools/blob/bcbc01e07a207df14492cc7e79166e824c209f0d/internal/imports/fix.go#L1185

**Comment by edwarnicke** [comment]
I think this has been resolved with the resolution of #11
